# -*- coding: utf-8 -*-
"""Cópia de Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DLKBRqhSNXKAuvtKamaJzRDwsi0xh31S
"""

import pandas as pd
from IPython.display import display
tabela = pd.read_csv("ClientesBanco.csv", encoding="latin1")
display(tabela)

tabela = tabela.dropna()
display(tabela.info())
display(tabela.describe().round(1))

import plotly.express as px
grafico = px.histogram(tabela, x="Contatos 12m", color="Categoria")
grafico.show()